language: node_js
node_js:
  - "stable"

# Commands to install dependencies and build the project
script:
  - npm install
  - npm run build

# Deployment to GitHub Pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token   # Set this in Travis environment variables
  local_dir: build
  on:
    branch: main
